services:
  authservice:
    build:
      context: "/home/mikhail/RiderProjects/MicroSystem"
      dockerfile: AuthService/Dockerfile
    container_name: aspnet-authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__RegisterDbContext=Host=postgres;Port=5432;Database=users;Username=postgres;Password=123
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: users
    volumes:
      - pgdata:/var/opt/postgres
    networks:
      - app-network
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - grafana-data:/var/lib/grafana
             
volumes:
  pgdata:
  grafana-data:
    
networks:
  app-network:
    driver: bridge